spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: fkaya123

logging:
  level:
    root: INFO
    com:
      fnkaya:
        projectmanagement: DEBUG

security:
  jwt:
    secretKey: project.management.system.jwt.token.authentication.key